# NumPy Exercises for Data Analysis(Python)


### 1. Import numpy as np and see the version
     Difficulty Level: L1
     Q. Import numpy as 'np' and print the version number.
### SOLUTION :

In [1]:
import numpy as np
print(np.__version__)

1.16.4


### 2. How to create a 1D array?
    Difficulty Level: L1
    Q. Create a 1D array of numbers from 0 to 9
    
### SOLUTION : 

In [3]:
import numpy as np
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


## 3. How to create a boolean array?
    Difficulty Level: L1
    Q. Create a 3×3 numpy array of all True’s
### SOLUTION :

In [5]:
import numpy as np
a = np.array([6,7,8,9])
print([a>5])

[array([ True,  True,  True,  True])]


## 4. How to extract items that satisfy a given condition from 1D array?
    Difficulty Level: L1
    Q. Extract all odd numbers from arr
### SOLUTION :

In [6]:
import numpy as np
a = np.array([3,4,5,6,7,8,9])
b = a[a%2==0]
print(b)

[4 6 8]


## 5. How to replace items that satisfy a condition with another value in numpy array?
    Difficulty Level: L1
    Q. Replace all odd numbers in arr with -1
### SOLUTION :

In [7]:
import numpy as np
a = np.array([3,4,5,6,7,8,9])
a[a%2==0]=-1
print(a)

[ 3 -1  5 -1  7 -1  9]


## 6. How to replace items that satisfy a condition without affecting the original array?
    Difficulty Level: L2
    Q. Replace all odd numbers in arr with -1 without changing arr
### SOLUTION :

In [8]:
import numpy as np
a = np.array([3,4,5,6,7,8,9])
b=np.where(a%2==0,-1,a.copy())
print(b)
print(a)

[ 3 -1  5 -1  7 -1  9]
[3 4 5 6 7 8 9]


## 7. How to reshape an array?
    Difficulty Level: L1
    Q. Convert a 1D array to a 2D array with 2 rows
### SOLUTION :

In [9]:
import numpy as np
i = int(input("Enter your rows : "))
j = int(input("Enter your columns : "))
try :
    a = np.arange(10).reshape(i,j)
    print(a)
except :
    print("Invalid arrangment !")

Enter your rows : 5
Enter your columns : 2
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


## 8. How to stack two arrays vertically?
    Difficulty Level: L2
    Q. Stack arrays a and b vertically
### SOLUTION :

In [11]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
print(np.vstack((a,b)))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 9. How to stack two arrays horizontally?
    Difficulty Level: L2
    Q. Stack the arrays a and b horizontally.
### SOLUTION :

In [12]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
print(np.hstack((a,b)))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## 10. How to generate custom sequences in numpy without hardcoding?
    Difficulty Level: L2
    Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
### SOLUTION :

In [187]:
import numpy as np
a = np.array([1,2,3])
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## 11. How to get the common items between two python numpy arrays?
    Difficulty Level: L2
    Q. Get the common items between a and b
### SOLUTION : 

In [15]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a,b)
print(c)

[2 4]


## 12. How to remove from one array those items that exist in another?
    Difficulty Level: L2
    Q. From array a remove all items present in array b
### SOLUTION :

In [16]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a,b)
print(c)

[1 2 3 4]


## 13. How to get the positions where elements of two arrays match?
    Difficulty Level: L2
    Q. Get the positions where elements of a and b match
### SOLUTION :    

In [20]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.where(a==b)
print(c)

(array([1, 3, 5, 7], dtype=int64),)


## 14. How to extract all numbers between a given range from a numpy array?
    Difficulty Level: L2
    Q. Get all items between 5 and 10 from a.
### SOLUTION :

In [24]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a[np.where((a >=5) & (a <= 10))])

[ 6  9 10]


## 15. How to make a python function that handles scalars to work on numpy arrays?
    Difficulty Level: L2
    Q. Convert the function maxx that works on two scalars, to work on two arrays.
### SOLUTION :

In [30]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

A = np.vectorize(maxx,otypes=[float])
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
A(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

## 16. How to swap two columns in a 2d numpy array?
    Difficulty Level: L2
    Q. Swap columns 1 and 2 in the array arr.
### SOLUTION :    

In [36]:
arr = np.arange(9).reshape(3,3)
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

## 17. How to swap two rows in a 2d numpy array?
    Difficulty Level: L2
    Q. Swap rows 1 and 2 in the array arr:
### SOLUTION :

In [37]:
arr = np.arange(9).reshape(3,3)
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

## 18. How to reverse the rows of a 2D array?
    Difficulty Level: L2
    Q. Reverse the rows of a 2D array arr.
### SOLUTION :

In [38]:
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

## 19. How to reverse the columns of a 2D array?
    Difficulty Level: L2
    Q. Reverse the columns of a 2D array arr.
### SOLUTION :

In [39]:
arr = np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

## 20. How to create a 2D array containing random floats between 5 and 10?
    Difficulty Level: L2
    Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
### SOLUTION :

In [41]:
np.random.uniform(5,10, size = (5,3))

array([[6.67179682, 9.54371701, 5.01242155],
       [8.22311685, 6.28867668, 7.36485865],
       [9.65024808, 6.26493692, 5.67545153],
       [8.37208225, 7.06861478, 7.77493749],
       [5.94036686, 8.38158039, 9.77737322]])

## 21. How to print only 3 decimal places in python numpy array?
    Difficulty Level: L1
    Q. Print or show only 3 decimal places of the numpy array rand_arr.
### SOLUTION :

In [44]:
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr[:2]

array([[0.443, 0.182, 0.278],
       [0.494, 0.266, 0.532]])

## 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?
    Difficulty Level: L1
    Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)
### SOLUTION :

In [47]:
# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr
#> array([[ 5.434049e-04, 2.783694e-04, 4.245176e-04],
#> [ 8.447761e-04, 4.718856e-06, 1.215691e-04],
#> [ 6.707491e-04, 8.258528e-04, 1.367066e-04]])
np.set_printoptions(suppress=True, precision=6)
print(rand_arr)


[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


## 23. How to limit the number of items printed in output of numpy array?
    Difficulty Level: L1
    Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.
### SOLUTION :

In [4]:
import numpy as np
np.set_printoptions(threshold=6)
a = np.arange(15)
print(a)

[ 0  1  2 ... 12 13 14]


## 24. How to print the full numpy array without truncating
    Difficulty Level: L1
    Q. Print the full numpy array a without truncating.
### SOLUTION :

In [7]:
np.set_printoptions(threshold=6)
a = np.arange(15)
np.set_printoptions(threshold = 15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?
    Difficulty Level: L2
    Q. Import the iris dataset keeping the text intact.
### SOLUTION :

In [21]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
iris_1d[:4]

/home/animesh/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, b'Iris-setosa')],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8'), ('f3', '<f8'), ('f4', 'S15')])

## 26. How to extract a particular column from 1D array of tuples?
    Difficulty Level: L2
    Q. Extract the text column species from the 1D iris imported in previous question.
### SOLUTION :

In [15]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d.shape)
oned_array = np.array([row[3] for row in iris_1d])
oned_array[:4]

(150,)


/home/animesh/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([0.2, 0.2, 0.2, 0.2])

## 27. How to convert a 1d array of tuples to a 2d numpy array?
    Difficulty Level: L2
    Q. Convert the 1D iris to 2D array iris_2d by omitting the species text field.
### SOLUTION :

In [8]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
nd = np.array([row.tolist()[:5] for row in iris_1d])
nd[:5]

/home/animesh/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa']], dtype='|S32')

## 28. How to compute the mean, median, standard deviation of a numpy array?
    Difficulty: L1
    Q. Find the mean, median, standard deviation of iris's sepallength (1st column)
### SOLUTION :

In [12]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
convetor = np.genfromtxt(url, delimiter=',', dtype='float', usecols =0)
print(np.mean(convetor))
print(np.median(convetor))
print(np.std(convetor))

5.843333333333334
5.8
0.8253012917851409


## 29. How to normalize an array so the values range exactly between 0 and 1?
    Difficulty: L2
    Q. Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the           minimum has value 0 and maximum has value 1.
### SOLUTION :

In [20]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
normalized = (sepallength-np.min(sepallength))/np.ptp(sepallength)
print(normalized)

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

## 30. How to compute the softmax score?
    Difficulty Level: L3
    Q. Compute the softmax score of sepallength.
### SOLUTION :    

In [28]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    print(e_x / e_x.sum())
softmax(sepallength)

[0.00221959 0.00181724 0.00148783 0.00134625 0.00200836 0.00299613
 0.00134625 0.00200836 0.00110221 0.00181724 0.00299613 0.00164431
 0.00164431 0.00099732 0.0044697  0.00404435 0.00299613 0.00221959
 0.00404435 0.00221959 0.00299613 0.00221959 0.00134625 0.00221959
 0.00164431 0.00200836 0.00200836 0.00245302 0.00245302 0.00148783
 0.00164431 0.00299613 0.00245302 0.00331123 0.00181724 0.00200836
 0.00331123 0.00181724 0.00110221 0.00221959 0.00200836 0.00121813
 0.00110221 0.00200836 0.00221959 0.00164431 0.00221959 0.00134625
 0.00271101 0.00200836 0.01483991 0.00814432 0.01342771 0.00331123
 0.00900086 0.00404435 0.00736928 0.00181724 0.00994749 0.00245302
 0.00200836 0.00493978 0.0054593  0.00603346 0.00365948 0.01099368
 0.00365948 0.0044697  0.006668   0.00365948 0.00493978 0.00603346
 0.00736928 0.00603346 0.00814432 0.00994749 0.01214989 0.01099368
 0.0054593  0.00404435 0.00331123 0.00331123 0.0044697  0.0054593
 0.00299613 0.0054593  0.01099368 0.00736928 0.00365948 0.00331

## 31. How to find the percentile scores of a numpy array?
    Difficulty Level: L1
    Q. Find the 5th and 95th percentile of iris's sepallength
### SOLUTION :

In [29]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
np.percentile(sepallength, q=[5, 95])


array([4.6  , 7.255])

### 32. How to insert values at random positions in an array?
    Difficulty Level: L2
    Q. Insert np.nan values at 20 random positions in iris_2d dataset
### SOLUTION :

In [22]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print(iris_2d[:5])

[[5.1 3.5 1.4 0.2 nan]
 [4.9 3.  1.4 0.2 nan]
 [4.7 nan 1.3 0.2 nan]
 [4.6 3.1 1.5 0.2 nan]
 [5.  3.6 1.4 0.2 nan]]


## 33. How to find the position of missing values in numpy array?
    Difficulty Level: L2
    Q. Find the number and position of missing values in iris_2d's sepallength (1st column)
### SOLUTION :

In [12]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print(np.isnan(iris_2d[:,0]))

[False False False False False False False False False False False False
  True False False False False False False False False False False False
 False False False False False False  True False False False False  True
 False False False False False False False False False  True False False
 False False False  True False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False  True False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False]


## 34. How to filter a numpy array based on two or more conditions?
      Difficulty Level: L3
      Q. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
### SOLUTION :

In [21]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
a = ((iris_2d[:,2]>1.5)&(iris_2d[:,2]<5.0))
iris_2d[a][:5]

array([[5.4, 3.9, 1.7, 0.4],
       [4.8, 3.4, 1.6, 0.2],
       [5.7, 3.8, 1.7, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.3, 1.7, 0.5]])

## 35. How to drop rows that contain a missing value from a numpy array?
    Difficulty Level: L3:
    Q. Select the rows of iris_2d that does not have any nan value.
### SOLUTION :

In [20]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.sum(np.isnan(iris_2d), axis =1)==0][:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

### 36. How to find the correlation between two columns of a numpy array?
    Difficulty Level: L2
    Q. Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d
### SOLUTION :

In [25]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.corrcoef(iris_2d[:, 0], iris_2d[:, 2])[0,1]

0.8717541573048714

## 37. How to find if a given array has any null values?
Difficulty Level: L2
Q. Find out if iris_2d has any missing values.
### SOLUTION :

In [27]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.isnan(iris_2d).any()

False

## 38. How to replace all missing values with 0 in a numpy array?
    Difficulty Level: L2
    Q. Replace all ccurrences of nan with 0 in numpy array
### SOLUTION :

In [32]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
iris_2d[np.isnan(iris_2d)]=0
print(iris_2d[:5])

[[5.1 3.5 1.4 0. ]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


## 39. How to find the count of unique values in a numpy array?
    Difficulty Level: L2
    Q. Find the unique values and the count of unique values in iris's species
### SOLUTION :

In [37]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
a = np.array([row.tolist()[3] for row in iris])
np.unique(a, return_counts=True)

(array([b'0.1', b'0.2', b'0.3', b'0.4', b'0.5', b'0.6', b'1.0', b'1.1',
        b'1.2', b'1.3', b'1.4', b'1.5', b'1.6', b'1.7', b'1.8', b'1.9',
        b'2.0', b'2.1', b'2.2', b'2.3', b'2.4', b'2.5'], dtype='|S3'),
 array([ 6, 28,  7,  7,  1,  1,  7,  3,  5, 13,  8, 12,  4,  2, 12,  5,  6,
         6,  3,  8,  3,  3]))

## 40. How to convert a numeric to a categorical (text) array?
    Difficulty Level: L2
    Q. Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
        Less than 3 --> 'small'
        3-5 --> 'medium'
        '>=5 --> 'large'
### SOLUTION :

In [34]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

## 41. How to create a new column from existing columns of a numpy array?
    Difficulty Level: L2
    Q. Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
### SOLUTION :

In [48]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print(iris_2d[:4])
a = iris_2d[:,0].astype('float')
b = iris_2d[:,3].astype('float')
c = (np.pi*b*(a**2))/3
c = c[:,np.newaxis]
d =np.c_[iris_2d,c]
print(d[:4])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']]
[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa' 5.447521661324701]
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa' 5.028642640846063]
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa' 4.62651878118657]
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa' 4.431740036664]]


## 42. How to do probabilistic sampling in numpy?
    Difficulty Level: L3
    Q. Randomly sample iris's species such that setose is twice the number of versicolor and virginica
### SOLUTION :

In [49]:
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

## 43. How to get the second largest value of an array when grouped by another array?
    Difficulty Level: L2
    Q. What is the value of second longest petallength of species setosa
### SOLUTION :

In [50]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

## 44. How to sort a 2D array by a column
    Difficulty Level: L2
    Q. Sort the iris dataset based on sepallength column.
### SOLUTION :

In [56]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[iris[:,0].argsort()[:10]]

array([[b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'4.4', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'3.0', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.5', b'2.3', b'1.3', b'0.3', b'Iris-setosa'],
       [b'4.6', b'3.6', b'1.0', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'4.6', b'3.2', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

## 45. How to find the most frequent value in a numpy array?
    Difficulty Level: L1
    Q. Find the most frequent value of petal length (3rd column) in iris dataset.
### SOLUTION :

In [59]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
a,b = np.unique(iris[:, 2], return_counts=True)
print(b[np.argmax(a)])

1


## 46. How to find the position of the first occurrence of a value greater than a given value?
    Difficulty Level: L2
    Q. Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris           dataset.
### SOLUTION :

In [61]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
np.argwhere(iris[:, 3].astype(float) > 1.0)[0]

array([50])

## 47. How to replace all values greater than a given value to a given cutoff?
    Difficulty Level: L2
    Q. From the array a, replace all values greater than 30 to 30 and less than 10 to 10.
### SOLUTION :

In [62]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(np.where(a < 10, 10, np.where(a > 30, 30, a)))

[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]


## 48. How to get the positions of top n values from a numpy array?
    Difficulty Level: L2
    Q. Get the positions of top 5 maximum values in a given array a.
### SOLUTION :

In [69]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
np.sort(a)[-5:]

array([40.99501269, 41.466785  , 42.39403048, 44.67477576, 48.95256545])

## 49. How to compute the row wise counts of all possible values in an array?
    Difficulty Level: L4
    Q. Compute the counts of unique values row-wise.
### SOLUTION :

In [70]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr = np.array([[ 9, 9, 4, 8, 8, 1, 5, 3, 6, 3],
        [ 3, 3, 2, 1, 9, 5, 1, 10, 7, 3],
        [ 5, 2, 6, 4, 5, 5, 4, 8, 2, 2],
        [ 8, 8, 1, 3, 10, 10, 4, 3, 6, 9],
        [ 2, 1, 8, 7, 3, 1, 9, 3, 6, 2],
        [ 9, 2, 6, 5, 3, 9, 4, 6, 1, 10]])
def cr(ar):
    number = [np.unique(i, return_counts=True) for i in ar]
    return ([[int(b[a==j]) if j in a else 0 for j in np.unique(ar)] for a, b in number])
cr(arr)


[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

## 50. How to convert an array of arrays into a flat 1d array?
    Difficulty Level: 2
    Q. Convert array_of_arrays into a flat linear 1d array.
### SOLUTION :

In [72]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)
array_of_arrays = np.array([arr1, arr2, arr3])
print(array_of_arrays)
#> array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])], dtype=object)
arr = np.concatenate(array_of_arrays)
print(arr)

[array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]
[0 1 2 3 4 5 6 7 8 9]


## 51. How to generate one-hot encodings for an array in numpy?
    Difficulty Level L4
    Q. Compute the one-hot encodings (dummy binary variables for each unique value in the array)
### SOLUTION :

In [76]:
np.random.seed(101)
arr = np.random.randint(1,4, size=6)
# arr  np.array([2, 3, 2, 2, 2, 1])
#arr[np.arange(3), arr] = 1
(arr[:, None] == np.unique(arr)).view(np.int8)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]], dtype=int8)

##  52. How to create row numbers grouped by a categorical variable?
    Difficulty Level: L3
    Q. Create row numbers grouped by a categorical variable. Use the following sample from iris species as input.
### SOLUTION :

In [107]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small

"""for j in np.unique(species_small):
    for i,grp in enumerate(species_small[species_small == j]):
        print(i)"""
print([i for val in np.unique(species_small) for i,grp in enumerate(species_small[species_small==val])])


[0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 6]


## 53. How to create groud ids based on a given categorical variable?
    Difficulty Level: L4
    Q. Create group ids based on a given categorical variable. Use the following sample from iris species as           input.
### SOLUTION :

In [111]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small
a = []
b = np.unique(species_small)

for i in b:
    for j in species_small[species_small==i]:
        idg = np.argwhere(b == j).tolist()[0][0]
        a.append(idg)
print(a)

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2]


## 54. How to rank items in an array using numpy?
    Difficulty Level: L2
    Q. Create the ranks for the given numeric array a.
### SOLUTION :

In [122]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
(a)
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)
print(a.argsort().argsort())

[ 9  4 15  0 17 16 17  8  9  0]
[4 2 6 0 8 7 9 3 5 1]


## 55. How to rank items in a multidimensional array using numpy?
    Difficulty Level: L3
    Q. Create a rank array of the same shape as a given numeric array a.
### SOLUTION :

In [115]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
(a)
print(a.ravel().argsort().argsort().reshape(a.shape))

[[4 2 6 0 8]
 [7 9 3 5 1]]


## 56. How to find the maximum value in each row of a numpy array 2d?
    DifficultyLevel: L2
    Q. Compute the maximum for each row in the given array.
### SOLUTION :

In [121]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)
np.amax(a, axis =1)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]


array([9, 8, 6, 3, 9])

## 57. How to compute the min-by-max for each row for a numpy array 2d?
    DifficultyLevel: L3
    Q. Compute the min-by-max for each row for given 2d numpy array.
### SOLUTION :

In [125]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)
np.apply_along_axis(lambda x: np.min(x)/np.max(x), arr=a, axis=1)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]


array([0.44444444, 0.125     , 0.5       , 1.        , 0.11111111])

## 58. How to find the duplicate records in a numpy array?
    Difficulty Level: L3
    Q. Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First       time occurrences should be False.
### SOLUTION :

In [133]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print(('Array: ', a))
b = np.full(a.shape[0], True)
c = np.unique(a, return_index=True)[1]
b[c] = False
print(b)

('Array: ', array([0, 0, 3, 0, 2, 4, 2, 2, 2, 2]))
[False  True False  True False False  True  True  True  True]


## 59. How to find the grouped mean in numpy?
    Difficulty Level L3
    Q. Find the mean of a numeric column grouped by a categorical column in a 2D numpy array
### SOLUTION :

In [148]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
a = iris[:,1].astype('float')
b = iris[:,4]
c = []
for i in np.unique(b) :
    c.append([i,a[b==i].mean()])
c

[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.7700000000000005],
 [b'Iris-virginica', 2.974]]

## 60. How to convert a PIL image to numpy array?
    Difficulty Level: L3
    Q. Import the image from the following URL and convert it to a numpy array.
### SOLUTION :

In [154]:
from io import BytesIO
from PIL import Image
import PIL, requests
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
conn = requests.get(URL)
a = Image.open(BytesIO(conn.content))
a = a.resize([100,100])
b = np.asarray(a)
print(b)
c = PIL.Image.fromarray(np.uint8(b))
Image.Image.show(c)

[[[ 10  73 126]
  [ 11  74 127]
  [ 10  73 126]
  ...
  [ 44 104 154]
  [ 44 104 154]
  [ 42 103 147]]

 [[ 11  74 127]
  [ 12  75 128]
  [ 11  74 127]
  ...
  [ 46 106 156]
  [ 46 106 156]
  [ 47 108 155]]

 [[ 11  74 127]
  [ 13  76 129]
  [ 12  75 128]
  ...
  [ 48 108 158]
  [ 48 108 158]
  [ 48 108 158]]

 ...

 [[ 33  51  63]
  [ 17  48  68]
  [ 21  56  78]
  ...
  [ 15  57  82]
  [  9  53  82]
  [ 12  50  73]]

 [[ 62  82  93]
  [ 26  45  59]
  [ 23  45  56]
  ...
  [  6  33  52]
  [ 15  37  48]
  [ 12  38  55]]

 [[ 27  56  72]
  [ 28  59  77]
  [ 41  73  88]
  ...
  [ 16  62  98]
  [ 35  79 106]
  [ 33  70  97]]]


## 61. How to drop all missing values from a numpy array?
    Difficulty Level: L2
    Q. Drop all nan values from a 1D numpy array
### SOLUTION :

In [156]:
a =np.array([1,2,3,np.nan,5,6,7,np.nan])
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])

## 62. How to compute the euclidean distance between two arrays?
    Difficulty Level: L3
    Q. Compute the euclidean distance between two arrays a and b.
### SOLUTION :

In [157]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
c = np.linalg.norm(a-b)
c

6.708203932499369

## 63. How to find all the local maxima (or peaks) in a 1d array?
    Difficulty Level: L4
    Q. Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.
### SOLUTION :

In [163]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
b = np.diff(np.sign(np.diff(a)))
c = np.where(b == -2)[0] + 1
c

array([2, 5])

## 64. How to subtract a 1d array from a 2d array, where each item of 1d array subtracts from respective row?
    Difficulty Level: L2
    Q. Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row     of a_2d.
### SOLUTION :

In [167]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,1,1])
print(a_2d - b_1d)

[[2 2 2]
 [3 3 3]
 [4 4 4]]


## 65. How to find the index of n'th repetition of an item in anarray
    Difficulty Level L2
    Q. Find the index of 5th repetition of number 1 in x.
### SOLUTION :

In [168]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5
np.where(x == 1)[0][n-1]

8

## 66. How to convert numpy's datetime64 object to datetime's datetime object?
    Difficulty Level: L2
    Q. Convert numpy's datetime64 object to datetime's datetime object
### SOLUTION :

In [173]:
import datetime
# Input: a numpy datetime64 object
dt64 = np.datetime64('2018-02-25 22:10:10')
dt64.tolist()

datetime.datetime(2018, 2, 25, 22, 10, 10)

## 67. How to compute the moving average of a numpy array?
    Difficulty Level: L3
    Q. Compute the moving average of window size 3, for the given 1D array.
### SOLUTION :

In [174]:
np.random.seed(100)
Z = np.random.randint(10, size=10)

## 68. How to create a numpy array sequence given only the starting point, length and the          step?
    Difficulty Level: L2
    Q. Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers
### SOLUTION :

In [178]:
l = 10
s = 5
b = 3
e = l *(s-b)
arr = np.arange(s,e,b)
print(arr)

[ 5  8 11 14 17]


## 69. How to fill in missing dates in an irregular series of numpy dates?
    Difficulty Level: L3
    Q. Given an array of a non-continuous sequence of dates. Make it a continuous sequence of dates, by filling         in the missing dates.
### SOLUTION :

In [181]:
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)
print(dates)
a = np.array([np.arange(i, (i+j)) for i,j in zip(dates, np.diff(dates))]).reshape(-1)
b = np.hstack([a,dates])
print(b)

['2018-02-01' '2018-02-03' '2018-02-05' '2018-02-07' '2018-02-09'
 '2018-02-11' '2018-02-13' '2018-02-15' '2018-02-17' '2018-02-19'
 '2018-02-21' '2018-02-23']
['2018-02-01' '2018-02-02' '2018-02-03' '2018-02-04' '2018-02-05'
 '2018-02-06' '2018-02-07' '2018-02-08' '2018-02-09' '2018-02-10'
 '2018-02-11' '2018-02-12' '2018-02-13' '2018-02-14' '2018-02-15'
 '2018-02-16' '2018-02-17' '2018-02-18' '2018-02-19' '2018-02-20'
 '2018-02-21' '2018-02-22' '2018-02-23']


## 70. How to create strides from a given 1D array?
    Difficulty Level: L4
    Q. From the given 1d array arr, generate a 2d matrix using strides, with a window length of 4 and strides of       2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]
### SOLUTION :

In [186]:
arr = np.arange(15)
print(arr)
b = np.lib.stride_tricks.as_strided(arr, (4,4), (0, 8))
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
