## 1.Write a NumPy program to get the numpy version and show numpy build configuration.
### SOLUTION :

In [1]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.16.4
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/animesh/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/animesh/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/animesh/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/animesh/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/animesh/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/animesh/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/animesh/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/animesh/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/animesh/anacon

## 2. Write a NumPy program to get help on the add function.
### SOLUTION :

In [2]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

## 3. Write a NumPy program to test whether none of the elements of a given array is zero.
### SOLUTION :

In [3]:
a = np.array([1,2,3,4,56])
print(np.all(a))

True


## 4. Write a NumPy program to test if any of the elements of a given array is non-zero.
### SOLUTION :

In [4]:
a = np.array([1,0,0,0])
print(np.any(a))

True


## 5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or          not a Number).
### SOLUTION :

In [7]:
a = np.arange(10).reshape(2,5)
print(a)
print(np.isfinite(a))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]]


## 6. Write a NumPy program to test element-wise for positive or negative infinity.
### SOLUTION :

In [15]:
a = np.array([-np.inf,1,-2,3,-4,np.inf])
print(np.isinf(a))

[ True False False False False  True]


## 7. Write a NumPy program to test element-wise for NaN of a given array.
### SOLUTION :

In [17]:
a = np.array([-np.inf,1,-2,3,-4,np.inf,np.NaN])
print(np.isnan(a))

[False False False False False False  True]


## 8. Write a NumPy program to test element-wise for complex number, real number of a                  given array. Also test if a given number is a scalar type or not.
### SOLUTION :

In [21]:
a = np.array([1+1j,4+1j,3.5,1.2,3])
print(np.iscomplex(a))
print(np.isreal(a))
print(np.isscalar(3.4))

[ True  True False False False]
[False False  True  True  True]
True


## 9. Write a NumPy program to test if two arrays are element-wise equal within a tolerance.
### SOLUTION :

In [ ]:
print(np.allcolose([1.e10,2]))

## 10. Write a NumPy program to create an element-wise comparison (greater, greater_equal,           less and less_equal) of two given arrays.
### SOLUTION :

In [26]:
a= np.array([1,2,3])
b = np.array([6,7,3])
print(np.greater(b,a))
print(np.greater_equal(b,a))
print(np.less(a,b))
print(np.less_equal(a,b))

[ True  True False]
[ True  True  True]
[ True  True False]
[ True  True  True]


## 11. Write a NumPy program to create an element-wise comparison (equal, equal within a              tolerance) of two given arrays.
### SOLUTION :

## 12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine              the size of the memory occupied by the array.
### SOLUTION :

In [30]:
a = np.array([1,7,13,105])
print(a)
#b=print(a.size)
#c=print(a.itemsize)
print(a.size*a.itemsize)

[  1   7  13 105]
32


## 13. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.
### SOLUTION :

In [32]:
print(np.zeros(10))
print(np.ones(10))
print(np.ones(10)*5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 14. Write a NumPy program to create an array of the integers from 30 to70.
### SOLUTION :

In [33]:
print(np.arange(30,71))

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


## 15. Write a NumPy program to create an array of all the even integers from 30 to 70.
### SOLUTION :

In [34]:
print(np.arange(30,71,2))

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


## 16. Write a NumPy program to create a 3x3 identity matrix.
### SOLUTION :

In [35]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 17. Write a NumPy program to generate a random number between 0 and 1.
### SOLUTION :

In [40]:
print(np.random.normal(0,1))

0.6369109851237058


## 18. Write a NumPy program to generate an array of 15 random numbers from a standard              normal distribution.
### SOLUTION :

In [41]:
print(np.random.normal(0,100,15))

[ -48.70208085    5.68655108   78.65581834  -33.32377703   30.15822497
  -68.02702242   94.24516455  136.16718012   35.38432251 -179.03610794
  116.2841911   -65.60758475   52.05752469  -89.21794955  -40.67907511]


## 19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print               all values except the first and last.
### SOLUTION :

In [48]:
a = np.arange(15,55)
print(a)
print(a[1:-1])

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


## 20. Write a NumPy program to create a 3X4 array using and iterate over it.
### SOLUTION :

In [54]:
a = np.arange(10,20).reshape((5,2))
print(a)
for i in np.nditer(a):
    print(i,end=' ')

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
10 11 12 13 14 15 16 17 18 19 